### ISSUE TITLE
Error con la conexión de la base de datos.

### ISSUE THREAD

**Issue by PabloMuYAnYO** [PabloMuYAnYO/nodejs-mongodb-notes#1]
Tratando de conectar la base de datos de mongo (dbConnection.js)

Mensaje de error:
'Error in DB connection: MongooseServerSelectionError: connect ECONNREFUSED ::1:27017'

![Captura de pantalla 2023-02-21 175353](https://user-images.githubusercontent.com/99806891/220409539-c3ca324e-88ed-48cb-bda9-bb42a1e51f53.jpg)

**Comment by PikaCode5900** [comment]
Error solucionado.

Cambio de host necesario en las variables de entorno.

![Captura de pantalla 2023-02-21 180342](https://user-images.githubusercontent.com/91385901/220411843-1ee34580-67c8-4791-b729-e3b05584b119.jpg)
